### PR TITLE
[Proposal] Configure health check to work with Istio Auth

### PR DESCRIPTION
**Pull request by gytis**
I've tried to run this booster on a cluster with Istio Auth enabled and it's health checks kept failing. I suggest we adapt all the health check configurations to work with and without Istio Auth.

### CODE REVIEW

**Comment by geoand** [comment]
For those you aren't privy to the reasons why typical (HTTP) health checks don't work when Istio auth is enabled, I suggest checking out [this](https://istio.io/help/faq/security.html#k8s-health-checks)

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
Furthermore, [this](https://github.com/istio/istio/issues/4429) Istio issue describes possible solutions and directions that Istio might take to get around this issue.

**Review by metacosm — APPROVED** [review]
LGTM

**Comment by lincolnthree** [comment]
Interesting, so that's why some of our boosters failed once Auth was turned on? Looks good!

**Pull request merged**
